export default function About() {
    return (
        <>
        <h1>Sobre</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et odio finibus, dignissim mauris et, fermentum nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hac habitasse platea dictumst. Sed in diam elementum, faucibus diam eu, blandit dolor. Donec sagittis, purus ut lobortis vestibulum, nulla quam condimentum lacus, sed consequat leo augue sit amet elit. Vivamus scelerisque tempus lobortis. Nunc dui purus, mattis at lacus quis, suscipit porta lectus. Praesent nibh ligula, commodo eget ante vel, vehicula euismod neque. Ut blandit elit in leo elementum mattis. Etiam nec metus aliquet, facilisis ante suscipit, vulputate arcu. Aliquam hendrerit arcu eget nulla sodales, scelerisque finibus justo imperdiet. Sed est magna, eleifend placerat felis pharetra, gravida lobortis lacus. </p>
        <p>Nulla ultricies molestie orci id vestibulum. Nam eget accumsan lacus. Phasellus ullamcorper laoreet dui non tristique. Donec elementum sem ac dignissim scelerisque. Praesent pretium nec neque ac consequat. Nam congue, dolor quis mattis mattis, sem magna tristique lorem, non sodales lorem diam a neque. Aliquam sed ultrices risus. Sed ultricies erat nec risus egestas accumsan. Nulla nisi quam, vulputate in eros at, bibendum vulputate nunc. In vel mauris sed ante dictum placerat id quis diam. Vivamus tempus leo et ornare pharetra. Curabitur vel placerat est. Vestibulum pharetra eros quis justo varius dapibus. Pellentesque ac congue eros. Praesent venenatis augue est, vitae aliquam turpis laoreet eu. </p>
        <p> Suspendisse rutrum purus a varius luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat lectus quis nulla volutpat sagittis. Nunc eros purus, pharetra id dapibus vitae, consequat eu eros. Integer eget nisl quis lorem mattis rutrum. In tempor facilisis egestas. Donec sagittis est quam, suscipit placerat velit tempor quis. Nulla non libero venenatis, sagittis dui eu, tincidunt justo. Nunc rhoncus magna nisl, in semper sem dapibus sed. Sed quis ultrices urna. Proin nunc mauris, hendrerit nec convallis placerat, blandit at justo. Praesent aliquet venenatis purus. Donec sodales urna in porttitor varius. Aenean porttitor diam pharetra tempus semper. Vestibulum tristique posuere finibus. Phasellus ipsum neque, tristique congue placerat vel, tincidunt sed enim. </p>
        <p> Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam dictum eros at leo posuere varius. Sed et accumsan mi. Nulla vel nisi id lectus commodo tempor. Aliquam sit amet sapien vel massa volutpat fermentum. Vestibulum commodo venenatis sem, nec tempus dui volutpat in. Aliquam eleifend iaculis nisi ac porttitor. Suspendisse non velit at quam tempus cursus. Sed massa eros, bibendum nec justo at, lacinia finibus ligula. Donec vitae ullamcorper nisi. Suspendisse et mauris in est scelerisque malesuada ultrices eget felis. Praesent quam ex, interdum tincidunt justo vitae, bibendum consectetur est. Phasellus convallis quam ante. In hac habitasse platea dictumst. Duis commodo dolor at est pulvinar mollis. Pellentesque porta maximus nisl. </p>
        <p> Quisque eleifend vel est sit amet semper. Quisque et ante dolor. Vivamus a luctus tellus. Cras eu quam egestas felis finibus commodo. Nullam quis mauris sodales, tincidunt quam ac, rhoncus sem. Pellentesque convallis nibh nec consequat pretium. Sed rutrum luctus felis vel interdum. Vivamus a eros lobortis, malesuada erat ac, convallis neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis eu est dui. Integer ultricies vel magna id hendrerit. </p>
        </> 
    )
}